version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: OL
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/OL
      JWT_SECRET: clave_local_segura
      JWT_EXPIRATION: 1d
      PORT: 3000
      NODE_ENV: development
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod

volumes:
  pgdata:
