version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: OL
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:lgSvDKEOgRUfaXrkbtKxEAcHbeoBRKmo@postgres.railway.internal:5432/railway
      JWT_SECRET: dev_secret_key_123
      JWT_EXPIRATION: 1d
      PORT: 3000
      NODE_ENV: production
      CORS_ORIGIN: "*"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: ./scripts/init-db.sh

volumes:
  pgdata:
